name: CI
on:
  push:
    branches: [ "master", "feature/**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy file transfer by scp
        uses: siva1024/scp-deployer@latest
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          source: "/home/runner/work/do-it-server/do-it-server/deploy/deploy.sh"
          target: "/home/ubuntu/do-it-deploy/script/server/deploy.sh"

      - uses: actions/checkout@master
      - name: compose-red file transfer by scp
        uses: siva1024/scp-deployer@latest
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          source: "/home/runner/work/do-it-server/do-it-server/deploy/docker-compose/docker-compose.red.yml"
          target: "/home/ubuntu/do-it-deploy/docker/server/"

      - uses: actions/checkout@master
      - name: compose-green file transfer by scp
        uses: siva1024/scp-deployer@latest
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          source: "/home/runner/work/do-it-server/do-it-server/deploy/docker-compose/docker-compose.green.yml"
          target: "/home/ubuntu/do-it-deploy/docker/server/"

      - name: deploy docker image to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          script: |
            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKER_REPO}}
            sudo chmod -R 775 do-it-deploy
            BASH_RESULT=$(sh /home/ubuntu/do-it-deploy/script/server/deploy.sh | tail -1)
            echo "${BASH_RESULT}"
    
